In [55]:
import numpy as np

In [79]:
# Function to check if a specific number can be placed in a cell

def check_field(r, c, x):
    global m
    # Check the row
    for i in range(0,9):
        if m[r][i] == x:
            return False

    # Check the column
    for i in range(0,9):
        if m[i][c] == x:
            return False

    # Check the box
    r_ = (r // 3) * 3
    c_ = (c // 3) * 3

    for i in range(0,3):
        for j in range(0,3):
            if m[r_+i][c_+j] == x:
                return False

    return True

# check_field(0, 2, 4)


In [ ]:
# Check which and how many numbers can be put in a specific field
# 

In [119]:
# Define the solver

def solve_Sudoku():
    global m
    global i

    for r in range(9):
        for c in range(9):
            if m[r][c] == 0:
                for n in range(1, 10):
                    if check_field(r, c, n):
                        # Enter value
                        m[r][c] = n

                        # Check next cells
                        solve_Sudoku()

                        # Reached dead end
                        m[r][c] = 0

                return

    i = i + 1
    if print_m:
        print(np.matrix(m))
        print(i)

In [122]:
# Wrap solver to allow for benchmarking
def solve_Sudoku_bench(m_, print_matrix = False):
    global m
    global i
    global print_m
    print_m = print_matrix
    m = m_.copy()
    i = 0
    solve_Sudoku()

In [166]:
# Define Sudoku to be solved
# Easy

m_easy = [
    [0, 8, 6, 0, 1, 0, 0, 4, 3],
    [0, 0, 9, 0, 0, 7, 0, 6, 5],
    [0, 5, 2, 6, 0, 3, 0, 0, 0],
    [0, 7, 0, 0, 3, 0, 5, 0, 0],
    [0, 0, 0, 5, 9, 0, 4, 3, 0], 
    [0, 3, 5, 0, 0, 4, 0, 1, 0],
    [0, 0, 0, 8, 0, 1, 6, 0, 0],
    [6, 2, 7, 3, 0, 0, 1, 0, 8],
    [0, 9, 8, 0, 0, 6, 3, 7, 0]
]

solve_Sudoku_bench(m_easy, print_matrix = True)

[[7 8 6 9 1 5 2 4 3]
 [3 1 9 4 2 7 8 6 5]
 [4 5 2 6 8 3 7 9 1]
 [9 7 4 1 3 2 5 8 6]
 [2 6 1 5 9 8 4 3 7]
 [8 3 5 7 6 4 9 1 2]
 [5 4 3 8 7 1 6 2 9]
 [6 2 7 3 4 9 1 5 8]
 [1 9 8 2 5 6 3 7 4]]
1


In [204]:
# Medium
m_medium = [
    [0, 0, 2, 0, 0, 5, 0, 0, 3],
    [8, 6, 0, 7, 0, 2, 0, 0, 0],
    [5, 9, 1, 0, 3, 6, 0, 7, 0],
    [7, 3, 4, 0, 0, 0, 1, 0, 0],
    [6, 0, 0, 0, 2, 0, 0, 0, 4], 
    [0, 0, 8, 0, 0, 0, 5, 6, 7],
    [0, 4, 0, 6, 8, 0, 9, 3, 5],
    [0, 0, 0, 3, 0, 9, 0, 4, 8],
    [3, 0, 0, 2, 0, 0, 7, 0, 0]
]

solve_Sudoku_bench(m_medium, print_matrix = True)


[[4 7 2 8 1 5 6 9 3]
 [8 6 3 7 9 2 4 5 1]
 [5 9 1 4 3 6 8 7 2]
 [7 3 4 5 6 8 1 2 9]
 [6 1 5 9 2 7 3 8 4]
 [9 2 8 1 4 3 5 6 7]
 [2 4 7 6 8 1 9 3 5]
 [1 5 6 3 7 9 2 4 8]
 [3 8 9 2 5 4 7 1 6]]
1


In [126]:
# Hard

m_hard_1 = [
    [4, 6, 0, 2, 1, 8, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 8, 0],
    [7, 0, 3, 6, 0, 0, 5, 0, 0],
    [0, 0, 0, 0, 7, 3, 0, 0, 1],
    [0, 7, 0, 0, 0, 0, 0, 4, 0], 
    [2, 0, 0, 8, 6, 0, 0, 0, 0],
    [0, 0, 8, 0, 0, 1, 4, 0, 9],
    [0, 2, 0, 0, 0, 0, 0, 0, 6],
    [0, 0, 0, 4, 2, 6, 0, 5, 3]
]

solve_Sudoku_bench(m_hard_1, print_matrix = True)

[[4 6 5 2 1 8 9 3 7]
 [1 9 2 3 5 7 6 8 4]
 [7 8 3 6 4 9 5 1 2]
 [8 4 9 5 7 3 2 6 1]
 [5 7 6 1 9 2 3 4 8]
 [2 3 1 8 6 4 7 9 5]
 [6 5 8 7 3 1 4 2 9]
 [3 2 4 9 8 5 1 7 6]
 [9 1 7 4 2 6 8 5 3]]
1


In [128]:
#  Hard
# m_hard_2 = [
#     [6, 0, 0, 0, 0, 0, 0, 0, 0],
#     [0, 9, 0, 5, 0, 4, 0, 0, 6],
#     [1, 5, 8, 0, 2, 0, 0, 0, 0],
#     [0, 0, 0, 7, 4, 0, 0, 3, 1],
#     [0, 0, 0, 0, 0, 0, 0, 0, 0], 
#     [5, 2, 0, 0, 1, 9, 0, 0, 0],
#     [0, 0, 0, 0, 3, 0, 1, 6, 9],
#     [9, 0, 0, 6, 0, 2, 0, 8, 0],
#     [0, 0, 0, 0, 0, 0, 0, 0, 7]
# ]

# solve_Sudoku_bench(m_hard_2, print_matrix = True)

[[6 4 7 1 8 3 9 5 2]
 [3 9 2 5 7 4 8 1 6]
 [1 5 8 9 2 6 7 4 3]
 [8 6 9 7 4 5 2 3 1]
 [7 1 3 2 6 8 4 9 5]
 [5 2 4 3 1 9 6 7 8]
 [2 8 5 4 3 7 1 6 9]
 [9 7 1 6 5 2 3 8 4]
 [4 3 6 8 9 1 5 2 7]]
1


In [131]:
# Benchmarking
%timeit -n 50 solve_Sudoku_bench(m_easy)

1.53 ms ± 204 µs per loop (mean ± std. dev. of 7 runs, 50 loops each)


In [132]:
%timeit -n 50 solve_Sudoku_bench(m_medium)

908 µs ± 32 µs per loop (mean ± std. dev. of 7 runs, 50 loops each)


In [138]:
%timeit -n 50 solve_Sudoku_bench(m_hard_1)

16.8 ms ± 729 µs per loop (mean ± std. dev. of 7 runs, 50 loops each)


In [137]:
# %timeit -n 50 solve_Sudoku_bench(m_hard_2)

116 µs ± 22.5 µs per loop (mean ± std. dev. of 7 runs, 50 loops each)
